### PR TITLE
Make `noarch`

### LINKED ISSUE #1: Add `linux_ppc64le` packages
Opening to track addition of `linux_ppc64le` packages for `cuda-toolkit`. This depends on `cuda-tools` packages of `linux_ppc64le` being added ( https://github.com/conda-forge/cuda-tools-feedstock/issues/1 ). So this is currently blocked atm

### PR DESCRIPTION
**Pull request by adibbley**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Fixes #1

### CODE REVIEW

**Comment by adibbley** [comment]
@conda-forge-admin, please rerender

**Comment by adibbley** [comment]
Requires https://github.com/conda-forge/cuda-tools-feedstock/pull/4

**Review by jakirkham — APPROVED** [review]
Thanks Alex! 🙏

**Comment by jakirkham** [comment]
Forgot to enable `linux_ppc64le` in `conda-forge.yml`. Handling in PR: https://github.com/conda-forge/cuda-toolkit-feedstock/pull/6

**Pull request merged**
